収入項目:
- 給与A
- 給与B
支出項目:
- - 光熱水
  - - 電気
    - ガス
    - 水道
- - 通信
  - - 通信
- - 住居
  - - 住居
- - 医療・保険
  - - 保険
    - 医療
- - 食料品
  - - 食料品
- - 日用雑貨
  - - 日用雑貨
- - 交通
  - - 交通
- - 娯楽
  - - 娯楽
- - 交際
  - - 交際
- - NA
  - - その他
現在月:
- 2004
- 3
締め月:
- 2004
- 3
開始月:
- 2001
- 4
